theme: jekyll-theme-minimal
title: rowling's homepage
description: Bookmark this to keep an eye on my project updates!


navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
